[package]
name = "isbn2"
version = "0.3.1"
authors = ["Jihyeok Seo <limeburst@ridi.com>", "Philippe Solodov <solop1906@gmail.com>"]
description = "A library for handling ISBNs."
license = "MIT"
repository = "https://github.com/philippeitis/isbn-rs"
edition = "2018"

[build-dependencies]
codegen = "0.1"
roxmltree = "0.13.0"

[dependencies]
arrayvec = { version = "0.5.2", default-features = false }
quick-xml = { version = "0.20.0", optional = true }
indexmap = { version = "1.6.1", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
runtime-ranges = ["quick-xml", "indexmap"]
serialize = ["serde"]